dist: xenial
language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7.0"
env:
    global:
     - lutece_runtime_mode=travis
before_install:
    - mysql -u root -e "CREATE DATABASE IF NOT EXISTS runtime_test_db CHARACTER SET utf8 COLLATE utf8_general_ci;"
    - mysql -u root -e "CREATE USER 'test_user'@'localhost' IDENTIFIED BY 'lUtEcEtRaViSdB';"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'localhost';"
    - mysql -u root -e "FLUSH PRIVILEGES;"
    - cp Lutece/config.py.template Lutece/config.py
install:
    - pip install -r requirements/requirements.txt
    - pip install coveralls

script:
    # Database migrations / migrate test
    - python manage.py makemigrations user problem judge submission data article record reply contest wiki
    - python manage.py migrate
    # Coverage unit test
    - coverage run --source=./ manage.py test --noinput

after_success:
    - coveralls
